copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\Content\Story\Dialoge\DIA_VLK_436_Sonja.d" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\Content\Story\Dialoge"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\Content\Story\NPC\VLK_436_Sonja.d" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\Content\Story\NPC"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\Content\Items\IT_SonjaRune.d" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\Content\Items"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\Content\AI\Magic\Spells\Spell_SummonSonja.d" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\Content\AI\Magic\Spells"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\Content\AI\Magic\Spells\Spell_Teleport_Alle.d" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\Content\AI\Magic\Spells"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\Content\AI\Magic\Spell_ProcessMana.d" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\Content\AI\Magic"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\Content\Story\B_GiveTradeInv\B_GiveTradeInv_Sonja.d" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\Content\Story\B_GiveTradeInv"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\Content\Story\B_Story\B_GivePlayerXP.d" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\Content\Story\B_Story"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\Content\Story\B_Story\B_Enter_SonjaWorld.d" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\Content\Story\B_Story"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\Content\Story\NPC_Globals.d" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\Content\Story"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\Content\Story\Text.d" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\Content\Story"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\Content\Story\Startup.d" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\Content\Story"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\Content\Gothic.src" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\Content"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Worlds\Sonja\DieGestrandeten.zen" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Worlds\Sonja"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\_compiled\OUINFO.INF" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\_compiled"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\content\CUTSCENE\OU.BIN" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\content\CUTSCENE
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\_work\Data\Scripts\content\CUTSCENE\OU.CS" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\_work\Data\Scripts\content\CUTSCENE"
copy "C:\Program Files (x86)\Steam\steamapps\common\Gothic II\System\Sonja.ini" "C:\Users\Tamino\Documents\Projekte\g2-mod-sonja\System"

pause
